import type { Article } from './types';

export const articles: Article[] = [
  {
    slug: 'msme-90-day-growth-plan',
    title: 'How MSMEs Can Build a Practical 90-Day Business Growth Plan',
    summary: 'A structured approach to building a realistic 90-day growth plan that turns strategy into measurable action.',
    date: '2026-09-15',
    readingTime: '6 min read',
    keywords: 'MSME business growth plan, 90-day action plan, business strategy India',
    content: [
      'Many MSMEs set ambitious growth targets at the start of the year but struggle to translate them into concrete action. The result is a gap between intention and execution. A 90-day growth plan bridges that gap by breaking annual goals into focused, measurable quarterly sprints.',
      'The first step is to define your primary growth objective for the quarter. This should be specific and measurable — for example, "increase monthly revenue by 15%" or "add 20 new B2B customers." Avoid vague goals like "grow the business." A clear objective gives your team a shared target and makes it possible to track progress.',
      'Next, identify the two or three initiatives that will most directly contribute to that objective. Trying to do everything at once dilutes focus and resources. If your goal is revenue growth, your initiatives might be: improving sales conversion, launching a lead generation campaign, and increasing average order value. Each initiative should have an owner and a clear definition of success.',
      'For each initiative, break the work into weekly milestones. This is where most plans fail — they describe the destination but not the journey. Weekly milestones create accountability and let you course-correct early. For a lead generation campaign, week one might be defining your ideal customer profile, week two building a prospect list, week three reaching out, and week four following up and tracking responses.',
      'Define KPIs for each initiative and review them weekly. KPIs should be leading indicators, not just lagging ones. Revenue is a lagging indicator — by the time you see it, the work is already done. Leading indicators like number of sales calls made, proposals sent, or follow-up meetings scheduled tell you whether you are on track before the results show up.',
      'Schedule a weekly review meeting — 30 minutes is enough. Review KPIs, discuss what worked and what did not, and adjust the plan for the coming week. This cadence is what separates plans that gather dust from plans that drive growth.',
      'At the end of the 90 days, conduct a review. Did you achieve your objective? Which initiatives delivered results? What lessons can you carry into the next quarter? Use this review to set the next 90-day objective, and repeat the cycle.',
      'A 90-day plan is not about predicting the future perfectly — it is about creating a disciplined rhythm of planning, action, measurement and adjustment. That rhythm, sustained over several quarters, is what drives compounding growth for MSMEs.',
    ],
  },
  {
    slug: 'convert-leads-into-sales',
    title: 'Seven Reasons Businesses Struggle to Convert Leads into Sales',
    summary: 'Identify the common bottlenecks that prevent leads from becoming paying customers and learn how to fix them.',
    date: '2026-09-10',
    readingTime: '7 min read',
    keywords: 'lead conversion, sales process, B2B sales, sales improvement',
    content: [
      'Generating leads is only half the battle. Many businesses invest in marketing and lead generation but see poor conversion rates because their sales process has gaps. Here are seven common reasons leads do not convert — and what to do about each.',
      '1. No defined sales process. If every salesperson handles leads differently, there is no way to identify what works or improve it. A defined sales process with clear stages — from initial contact to qualification, proposal, follow-up and close — creates consistency and makes performance measurable.',
      '2. Slow response times. Research consistently shows that the speed of response to a new lead dramatically affects conversion rates. If your team takes hours or days to respond, the lead has often moved on. Aim to respond to inbound enquiries within minutes, not hours.',
      '3. Poor qualification. Not every lead is a good fit. Trying to sell to unqualified leads wastes time and lowers your conversion rate. Define your ideal customer profile and qualify leads early — understand their need, budget, authority and timeline before investing significant sales effort.',
      '4. Weak follow-up. Most sales do not happen on the first contact. They require multiple follow-ups over days or weeks. Many salespeople give up after one or two attempts. A structured follow-up cadence with a CRM ensures no lead falls through the cracks.',
      '5. Focusing on features instead of value. Customers do not buy features — they buy solutions to their problems. If your sales conversations focus on what your product does rather than what the customer gains, conversion suffers. Understand the customer\'s pain points and frame your offering as the solution.',
      '6. No CRM or tracking system. Without a system to track where each lead is in the pipeline, follow-ups are missed, opportunities are forgotten, and managers cannot identify bottlenecks. Even a simple CRM transforms sales performance by making the pipeline visible and manageable.',
      '7. Inconsistent sales messaging. If your team cannot clearly and consistently articulate your value proposition, customers get confused and lose confidence. Develop sales scripts, talking points and proposal templates that ensure every customer hears a clear, compelling message.',
      'Fixing these issues does not require a complete overhaul. Start by defining your sales process, implementing a CRM, and establishing a follow-up cadence. These three changes alone can significantly improve conversion rates within a quarter.',
    ],
  },
  {
    slug: 'kpi-driven-sales-team',
    title: 'How to Build a KPI-Driven Sales Team',
    summary: 'Transform your sales team from order-takers into a performance-driven engine using the right KPIs and review cadence.',
    date: '2026-09-05',
    readingTime: '6 min read',
    keywords: 'sales KPIs, sales team performance, sales management, KPI dashboard',
    content: [
      'A sales team without clear KPIs is like a sports team without a scoreboard — there is no way to know who is winning or what to improve. Building a KPI-driven sales team transforms performance by making expectations clear, progress visible, and coaching targeted.',
      'Start with activity KPIs. These are the leading indicators that your team controls directly: number of calls made, meetings booked, proposals sent, and follow-ups completed. Activity KPIs tell you whether your team is putting in the effort required to generate results.',
      'Next, define outcome KPIs. These are the results of the activities: leads generated, meetings held, proposals accepted, deals closed, and revenue. Outcome KPIs tell you whether the effort is producing results. If activity is high but outcomes are low, the issue is likely in skill or targeting, not effort.',
      'Track conversion ratios between stages. The ratio of calls to meetings, meetings to proposals, and proposals to closes reveals where your sales process is leaking. If you send many proposals but few close, your proposal or closing skills need attention. If meetings do not lead to proposals, your qualification or presentation needs work.',
      'Set individual and team targets. Each salesperson should have weekly activity targets and monthly outcome targets. Team targets create collective accountability, while individual targets ensure everyone contributes.',
      'Implement a weekly review cadence. Review individual and team KPIs every week. Celebrate wins, identify shortfalls, and plan specific coaching actions. The review is not about blame — it is about identifying what to improve and how to support each team member.',
      'Use a visible dashboard. Whether it is a CRM dashboard, a spreadsheet shared on screen, or a printed chart on the wall, making KPIs visible changes behaviour. When people can see their performance relative to targets and peers, motivation and accountability improve naturally.',
      'Coach based on KPIs. If a salesperson has low call volume, the coaching focus is on time management and prioritisation. If call volume is fine but meetings are low, the focus is on call quality and pitch. KPIs tell you exactly where to direct your coaching effort for maximum impact.',
      'Review and adjust KPIs quarterly. As your team matures and your business evolves, the right KPIs may change. What matters is that your KPIs always reflect the behaviours and outcomes that drive growth in your current context.',
    ],
  },
  {
    slug: 'evaluate-new-market',
    title: 'Business Expansion: How to Evaluate a New Market',
    summary: 'A practical framework for assessing whether a new market is worth entering and how to plan your expansion.',
    date: '2026-08-28',
    readingTime: '7 min read',
    keywords: 'market expansion, business growth, new market entry, expansion strategy India',
    content: [
      'Expanding into a new market — whether a new city, state or customer segment — is one of the most powerful ways to grow a business. But it is also one of the riskiest. A structured evaluation process helps you assess the opportunity before committing significant resources.',
      '1. Assess market size and demand. Is there genuine demand for your product or service in the target market? Research the number of potential customers, their spending patterns, and the total addressable market. Talk to potential customers directly — their feedback is more valuable than any report.',
      '2. Analyse the competitive landscape. Who is already serving this market? How strong are they? If the market is dominated by well-established competitors with loyal customers, your entry strategy needs to account for how you will differentiate and win share. If the market is underserved, the opportunity may be larger.',
      '3. Evaluate your readiness. Do you have the team, capital, operational capacity and supply chain to serve a new market? Expansion stretches every part of your business. If your current operations are already strained, expanding will make things worse, not better. Fix your foundation first.',
      '4. Understand the economics. What will it cost to enter and operate in this market? Consider setup costs, ongoing operational costs, pricing differences and expected margins. Build a financial model that shows how long it will take to reach break-even and what the investment looks like.',
      '5. Consider regulatory and logistical factors. Different states and cities may have different regulations, tax structures, licensing requirements and logistics costs. Understand these before you commit — surprises in compliance or logistics can derail an otherwise sound expansion.',
      '6. Choose your entry mode. Will you open a physical presence, partner with a local distributor, sell online, or acquire an existing local business? Each mode has different costs, risks and timeframes. Start with the lowest-risk mode that lets you validate demand before committing fully.',
      '7. Plan a phased entry. Rather than launching fully on day one, plan a phased approach. Start with a pilot — a single product line, a small team, or a limited geographic area. Learn from the pilot, refine your model, and then scale what works.',
      '8. Set clear milestones and exit criteria. Define what success looks like at 3, 6 and 12 months. If the market does not meet your milestones, know when to adjust or exit. Having clear criteria prevents the sunk-cost trap of continuing to invest in a market that is not working.',
      'Market expansion done well can transform your business. Done poorly, it can drain resources and distract from your core. The difference is in the quality of your evaluation and planning before you commit.',
    ],
  },
  {
    slug: 'revenue-gross-margin-cash-flow',
    title: 'Understanding Revenue, Gross Margin and Cash Flow',
    summary: 'Three financial concepts every business owner must understand to make informed decisions about growth and profitability.',
    date: '2026-08-20',
    readingTime: '5 min read',
    keywords: 'revenue, gross margin, cash flow, business finance, profitability',
    content: [
      'Many business owners focus on revenue and assume that if sales are growing, the business is healthy. But revenue alone tells you very little. Three financial concepts — revenue, gross margin and cash flow — together paint a complete picture of business health.',
      'Revenue is the total amount of money your business earns from selling products or services. It is the top line. Growing revenue is important, but revenue growth without profit growth is just growing costs. A business can have rising revenue and still be losing money.',
      'Gross margin is what remains after you subtract the direct cost of producing your product or service from your revenue. If you sell a product for ₹1,000 and it costs you ₹600 in materials and direct labour, your gross margin is ₹400, or 40%. Gross margin tells you how efficiently you are producing and pricing.',
      'Many businesses do not track gross margin by product or service line. They know total revenue and total costs but cannot see which products are profitable and which are dragging down overall performance. Understanding gross margin at a product level lets you make informed decisions about pricing, product mix and cost management.',
      'Cash flow is the movement of money in and out of your business. A profitable business can run out of cash if customers pay slowly, inventory builds up, or expenses are paid before revenue is collected. Cash flow problems are one of the most common reasons otherwise viable businesses fail.',
      'The relationship between these three is critical. You can have growing revenue and healthy gross margins but still face a cash flow crisis if your working capital is poorly managed. Conversely, you can have positive cash flow but declining gross margins, which means your business is slowly becoming unsustainable.',
      'To manage effectively, track all three regularly. Review revenue trends monthly. Monitor gross margin by product line quarterly. And maintain a rolling cash flow forecast so you can anticipate shortfalls before they happen. A 13-week cash flow forecast is a practical tool that gives you early warning of cash pressures.',
      'Understanding these three concepts does not require an accounting qualification. It requires the discipline to track them, review them, and use them to guide decisions. Business owners who understand their numbers make better decisions than those who rely on instinct alone.',
    ],
  },
  {
    slug: 'when-to-adopt-crm',
    title: 'When Should a Growing Business Adopt CRM Software?',
    summary: 'Signs that your business has outgrown spreadsheets and is ready for a CRM system to manage customer relationships and sales.',
    date: '2026-08-12',
    readingTime: '5 min read',
    keywords: 'CRM software, sales management, business technology, CRM implementation',
    content: [
      'Many growing businesses manage their customer relationships and sales pipeline using spreadsheets, WhatsApp or memory. This works for a while, but at some point it becomes a bottleneck. Knowing when to adopt a CRM system can save you from lost opportunities and stalled growth.',
      'Sign 1: You are losing track of leads. If you have ever forgotten to follow up with a prospect, lost a lead\'s contact details, or realised weeks later that an enquiry slipped through the cracks, you need a CRM. A CRM ensures every lead is captured, tracked and followed up.',
      'Sign 2: Your sales pipeline is invisible. If you cannot quickly answer "how many deals are in the pipeline and at what stage," you are managing sales blind. A CRM gives you a real-time view of your pipeline, making it possible to forecast revenue and identify bottlenecks.',
      'Sign 3: Multiple people are involved in sales. When one person handles all sales, a spreadsheet might suffice. But when two or more people are selling, you need shared visibility. A CRM ensures everyone can see the status of each lead and collaborate without duplication or gaps.',
      'Sign 4: You cannot measure sales performance. If you cannot track conversion rates, sales cycle length, or individual salesperson performance, you cannot improve what you cannot measure. A CRM automatically captures the data needed to calculate these metrics.',
      'Sign 5: Customer follow-ups are inconsistent. Different customers receive different levels of attention depending on who handles them and how busy they are. A CRM with automated reminders and follow-up sequences ensures consistent communication with every customer.',
      'Sign 6: Your business is growing. Growth multiplies the complexity of managing customer relationships. What is manageable with 50 customers becomes chaotic with 500. Adopting a CRM before you reach crisis point is far easier than trying to implement one when you are already overwhelmed.',
      'Choosing the right CRM does not mean buying the most expensive option. Start with a system that matches your current needs and can scale with you. Key features to look for include contact management, pipeline visualisation, follow-up reminders, reporting and mobile access.',
      'Implementation is as important as the software itself. The best CRM will fail if your team does not use it. Invest time in training, establish clear processes for entering and updating data, and make CRM usage a non-negotiable part of your sales routine. A partially-used CRM is no better than no CRM.',
      'If you recognise three or more of these signs in your business, it is likely time to adopt a CRM. The cost of a CRM is modest compared to the cost of lost leads, missed follow-ups and invisible pipelines.',
    ],
  },
  {
    slug: 'operational-inefficiencies',
    title: 'How to Identify Operational Inefficiencies',
    summary: 'A practical approach to finding and fixing the hidden inefficiencies that drain time, money and productivity from your business.',
    date: '2026-08-05',
    readingTime: '6 min read',
    keywords: 'operational efficiency, business operations, process improvement, cost reduction',
    content: [
      'Operational inefficiencies are like slow leaks — they drain resources gradually, often going unnoticed until the cumulative impact becomes significant. Identifying and fixing them is one of the fastest ways to improve profitability without needing to increase revenue.',
      '1. Map your core processes. Before you can identify inefficiencies, you need to understand how work actually flows through your business. Document each major process — from order intake to delivery, from lead generation to payment collection. You cannot fix what you cannot see.',
      '2. Look for bottlenecks. A bottleneck is any point where work piles up faster than it can be processed. If orders queue for days waiting for approval, or production stalls waiting for materials, you have a bottleneck. Bottlenecks dictate the speed of your entire operation — find and address them first.',
      '3. Identify redundant work. Are multiple people entering the same data into different systems? Are reports being generated that nobody reads? Are tasks being done manually that could be automated? Redundant work wastes time and introduces errors. Eliminate it wherever possible.',
      '4. Check for rework. Rwork — doing the same task twice because it was not done correctly the first time — is one of the most expensive inefficiencies. If products are being reworked, customer complaints require multiple rounds of resolution, or work is frequently sent back for revision, the root cause is usually unclear requirements or insufficient training.',
      '5. Analyse your cycle times. How long does it take to complete a task from start to finish? Long cycle times often indicate inefficiency. Compare your cycle times to industry benchmarks or to your own historical performance. Where you see long cycles, dig into the reasons.',
      '6. Review your resource utilisation. Are your people and equipment being used efficiently? Underutilised resources represent wasted investment, while overutilised resources create burnout and quality problems. Aim for balanced utilisation with some buffer capacity for peaks.',
      '7. Gather input from your team. The people who do the work every day know where the inefficiencies are. Ask them what slows them down, what they find frustrating, and what they would change. Frontline insights often reveal problems that managers miss.',
      '8. Prioritise improvements by impact. You will likely identify many inefficiencies. Not all are worth fixing — some are too small to matter, and some would cost more to fix than they save. Prioritise by the impact on cost, time or customer experience relative to the effort required.',
      '9. Implement standard operating procedures. Many inefficiencies exist because there is no standard way of doing things. SOPs ensure that work is done consistently and efficiently, regardless of who does it. They also make it easier to train new employees and identify further improvements.',
      'Operational improvement is not a one-time project — it is an ongoing discipline. The businesses that consistently outperform their peers are those that continually look for ways to work smarter, reduce waste and improve quality. Start with one process, fix it, and build from there.',
    ],
  },
  {
    slug: 'scalable-business-model-india',
    title: 'Building a Scalable Business Model in India',
    summary: 'Key principles for designing a business model that can grow efficiently without breaking under increased demand.',
    date: '2026-07-28',
    readingTime: '7 min read',
    keywords: 'scalable business model, business growth India, scaling a business, business architecture',
    content: [
      'Scalability is the ability of a business to grow without proportional increases in costs and complexity. A scalable business model allows you to serve 10 times more customers without needing 10 times the resources. In India\'s diverse and rapidly growing market, scalability is what separates businesses that grow smoothly from those that stall.',
      '1. Build systems before you need them. Many businesses add systems only after they encounter problems at scale. By then, the cost and disruption of retrofitting systems is much higher. Design your operational systems, processes and documentation early, even if they seem like overkill at your current size.',
      '2. Standardise your core processes. Scalability requires consistency. If every order, every customer interaction and every production run is handled differently, you cannot scale — each new customer adds unique complexity. Standardised processes let you handle more volume with the same approach.',
      '3. Reduce dependency on key individuals. If your business relies on one person\'s knowledge, relationships or skills, growth is limited by that person\'s capacity. Document knowledge, cross-train team members and build processes that work regardless of who executes them.',
      '4. Design for unit economics. Understand the cost and revenue of serving one additional customer. If your unit economics improve as you scale — because fixed costs are spread over more customers — your model is inherently scalable. If each new customer costs nearly as much to serve as the revenue they generate, your model does not scale.',
      '5. Leverage technology for repetitive tasks. Technology is the most powerful scalability lever. Tasks that are repetitive and rules-based — data entry, scheduling, reporting, customer communication — can be automated, freeing your team to focus on higher-value work that cannot be automated.',
      '6. Build a layered organisation. In a scalable business, the founder does not make every decision. Build clear organisational layers with defined authority and accountability. As the business grows, decisions are made at the appropriate level without everything depending on the top.',
      '7. Create a strong customer acquisition engine. Scalability is not just about operations — it is also about demand. A repeatable, measurable customer acquisition process that does not depend solely on the founder\'s personal network is essential for sustained growth.',
      '8. Plan your capital requirements. Scaling requires investment — in people, systems, inventory and infrastructure. Understand how much capital each stage of growth requires and secure it before you need it. Running out of capital mid-scale is a common reason businesses stall.',
      '9. Choose your market carefully. Some markets in India scale more easily than others. Markets with large, homogeneous customer bases and clear demand are easier to scale than fragmented, highly customised markets. Consider scalability when choosing which segments and geographies to target.',
      '10. Maintain quality as you grow. The biggest risk of scaling is that quality drops as volume increases. Quality problems lead to customer churn, reputation damage and rework costs that erase the benefits of scale. Build quality checks into your processes and monitor customer satisfaction continuously.',
      'Building a scalable business model is not about growth at all costs. It is about designing your business so that growth makes it stronger, not more fragile. The businesses that scale successfully in India are those that invest in systems, people and processes before they are urgently needed.',
    ],
  },
];

export function getArticle(slug: string): Article | undefined {
  return articles.find((a) => a.slug === slug);
}
